# Generated by Django 6.0.3 on 2026-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="game_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "3 sets à 6 jeux, jeu décisif à 6-6"),
                    ("A2", "3 sets à 6 jeux, point décisif, jeu décisif à 6-6"),
                    (
                        "B1",
                        "2 sets à 6 jeux, jeu décisif à 6-6, 3ème set = super jeu décisif à 10 points",
                    ),
                    (
                        "B2",
                        "2 sets à 6 jeux, point décisif, jeu décisif à 6-6, 3ème set = super jeu décisif à 10 points",
                    ),
                    (
                        "C1",
                        "2 sets à 4 jeux, jeu décisif à 4-4, 3ème set = super jeu décisif à 10 points",
                    ),
                    (
                        "C2",
                        "2 sets à 4 jeux, point décisif, jeu décisif à 4-4, 3ème set = super jeu décisif à 10 points",
                    ),
                    ("D1", "1 set à 9 jeux, jeu décisif à 8-8"),
                    ("D2", "1 set à 9 jeux, point décisif, jeu décisif à 8-8"),
                    ("E", "1 super jeu décisif à 10 points"),
                    ("F", "1 set à 4 jeux, point décisif, jeu décisif à 3-3"),
                ],
                default="",
                max_length=2,
            ),
        ),
    ]
