# Generated by Django 6.0.3 on 2026-03-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_game_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='configuration',
            field=models.CharField(blank=True, choices=[('TMC', 'Tournoi Multi Chance')], max_length=20, null=True),
        ),
    ]
