# Generated by Django 6.0.3 on 2026-06-06 09:09

from django.db import migrations, models


def backfill_pairs_count(apps, schema_editor):
    Tournament = apps.get_model("tournaments", "Tournament")
    from django.db.models import Count

    for t in Tournament.objects.annotate(pc=Count("pairs")):
        Tournament.objects.filter(pk=t.pk).update(pairs_count=t.pc)


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0006_add_status_to_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="pairs_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_pairs_count, migrations.RunPython.noop),
    ]
