# Generated by Django 6.0.3 on 2026-03-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('ranking', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='tournaments.tournament')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_player1', to='players.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_player2', to='players.player')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'player1'), name='unique_tournament_player1'), models.UniqueConstraint(fields=('tournament', 'player2'), name='unique_tournament_player2')],
            },
        ),
    ]
