# Generated by Django 6.0.3 on 2026-03-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFTRankingMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Mixte', 'Mixte')], max_length=10, unique=True)),
                ('last_imported_at', models.DateTimeField()),
                ('source_filename', models.CharField(max_length=255)),
                ('entry_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FFTRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, choices=[('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'), ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'), ('Bretagne', 'Bretagne'), ('Centre Val de Loire', 'Centre Val de Loire'), ('Corse', 'Corse'), ('Grand Est', 'Grand Est'), ('Guadeloupe', 'Guadeloupe'), ('Guyane', 'Guyane'), ('Hauts de France', 'Hauts de France'), ('Ile de France', 'Ile de France'), ('Martinique', 'Martinique'), ('Normandie', 'Normandie'), ('Nouvelle Aquitaine', 'Nouvelle Aquitaine'), ('Nouvelle Calédonie', 'Nouvelle Calédonie'), ('Occitanie', 'Occitanie'), ('Pays de la Loire', 'Pays de la Loire'), ("Provence-Alpes-Côtes d'Azur", "Provence-Alpes-Côtes d'Azur"), ('Réunion', 'Réunion')], max_length=50)),
                ('ranking', models.PositiveIntegerField()),
                ('points', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Mixte', 'Mixte')], max_length=10)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name', 'gender'], name='players_fft_last_na_afc04d_idx')],
            },
        ),
    ]
