# Generated by Django 6.0.3 on 2026-04-02 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_fftrankingmeta_fftranking'),
        ('tournaments', '0005_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.PositiveSmallIntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64')])),
                ('nb_top_seeds', models.PositiveSmallIntegerField(default=0)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_state', to='tournaments.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BracketSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_title', models.CharField(max_length=20)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_slots', to='players.pair')),
                ('bracket_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='brackets.bracketstate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bracket_state', 'slot_title'), name='uq_slot_per_bracket'), models.UniqueConstraint(fields=('bracket_state', 'pair'), name='uq_pair_per_bracket')],
            },
        ),
    ]
