# Generated by Django 6.0.3 on 2026-04-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketslot',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
