# Generated by Django 6.0.3 on 2026-05-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_fftrankingmeta_fftranking'),
        ('tournaments', '0006_add_status_to_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.PositiveSmallIntegerField(choices=[(8, '8'), (16, '16'), (32, '32'), (64, '64')])),
                ('nb_top_seeds', models.PositiveSmallIntegerField()),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='tournaments.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.CharField(choices=[('FINALE', 'Finale'), ('DEMI_FINALE', 'Demi-finale'), ('QUART_DE_FINALE', 'Quart de finale'), ('HUITIEME_DE_FINALE', 'Huitième de finale'), ('SEIZIEME_DE_FINALE', 'Seizième de finale'), ('TRENTE_DEUXIEME_DE_FINALE', '32ème de finale')], max_length=30)),
                ('match_number', models.PositiveSmallIntegerField()),
                ('game_format', models.CharField(blank=True, choices=[('A1', 'A1 : 3 sets à 6 jeux, jeu décisif à 6-6'), ('A2', 'A2 : 3 sets à 6 jeux, point décisif, jeu décisif à 6-6'), ('B1', 'B1 : 2 sets à 6 jeux, jeu décisif à 6-6, 3ème set = super jeu décisif à 10 points'), ('B2', 'B2 : 2 sets à 6 jeux, point décisif, jeu décisif à 6-6, 3ème set = super jeu décisif à 10 points'), ('C1', 'C1 : 2 sets à 4 jeux, jeu décisif à 4-4, 3ème set = super jeu décisif à 10 points'), ('C2', 'C2 : 2 sets à 4 jeux, point décisif, jeu décisif à 4-4, 3ème set = super jeu décisif à 10 points'), ('D1', 'D1 : 1 set à 9 jeux, jeu décisif à 8-8'), ('D2', 'D2 : 1 set à 9 jeux, point décisif, jeu décisif à 8-8'), ('E', 'E : 1 super jeu décisif à 10 points'), ('F', 'F : 1 set à 4 jeux, point décisif, jeu décisif à 3-3')], default='', max_length=2)),
                ('score', models.CharField(blank=True, default='', max_length=50)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.bracket')),
                ('child1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_as_child1', to='matches.match')),
                ('child2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_as_child2', to='matches.match')),
                ('pair1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_pair1', to='players.pair')),
                ('pair2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_pair2', to='players.pair')),
            ],
            options={
                'ordering': ['round', 'match_number'],
            },
        ),
    ]
