# Generated by Django 6.0.3 on 2026-06-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0003_rename_demi_finale_to_demie_finale"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="pair1_can_be_placed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="match",
            name="pair2_can_be_placed",
            field=models.BooleanField(default=True),
        ),
    ]
