# Generated by Django 6.0.3 on 2026-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0004_match_disabled_match_pair1_can_be_placed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bracket",
            name="nb_top_seeds",
        ),
        migrations.AddField(
            model_name="bracket",
            name="nb_pair_round_16",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bracket",
            name="nb_pair_round_32",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bracket",
            name="nb_pair_round_4",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bracket",
            name="nb_pair_round_64",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bracket",
            name="nb_pair_round_8",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
