# Generated by Django 6.0.3 on 2026-06-18 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_bracket_nb_top_seeds_bracket_nb_pair_round_16_and_more'),
        ('tournaments', '0007_add_pairs_count_to_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='end_place',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='matches.bracket'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='source_round',
            field=models.CharField(blank=True, choices=[('FINALE', 'Finale'), ('DEMIE_FINALE', 'Demies'), ('QUART_DE_FINALE', 'Quarts'), ('HUITIEME_DE_FINALE', 'Huitièmes'), ('SEIZIEME_DE_FINALE', 'Seizièmes'), ('TRENTE_DEUXIEME_DE_FINALE', '32èmes')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bracket',
            name='start_place',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='dimension',
            field=models.PositiveSmallIntegerField(choices=[(2, '2'), (4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64')]),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.tournament'),
        ),
    ]
