# Generated by Django 6.0.3 on 2026-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_bracket_end_place_bracket_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'À venir'), ('STARTED', 'En cours'), ('FINISHED', 'Terminé')], default='UPCOMING', max_length=10),
        ),
    ]
