# Generated by Django 6.0.3 on 2026-06-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0008_backfill_finished_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
